const { 
    ROLE_FREE_ID, 
    ROLE_PRO_MONTHLY,
    ROLE_PRO_YEARLY,
    ROLE_PRO_PLUS_MONTHLY,
    ROLE_PRO_PLUS_YEARLY,
    ROLE_TRIAL_PRO,
    ROLE_TRIAL_PRO_PLUS,
    ROLE_ULTIMATE_ID 
} = require('../config/env');
const { PLANS } = require('./plans');

/**
 * プランIDと環境変数上のロールIDを紐付けます。
 */
const PLAN_ROLE_MAP = {
    [PLANS.FREE.id]: ROLE_FREE_ID,
    [PLANS.PRO.id]: ROLE_PRO_MONTHLY,
    [PLANS.PRO_YEARLY.id]: ROLE_PRO_YEARLY,
    [PLANS.PRO_PLUS.id]: ROLE_PRO_PLUS_MONTHLY,
    [PLANS.PRO_PLUS_YEARLY.id]: ROLE_PRO_PLUS_YEARLY,
    [PLANS.TRIAL_PRO.id]: ROLE_TRIAL_PRO,
    [PLANS.TRIAL_PRO_PLUS.id]: ROLE_TRIAL_PRO_PLUS,
    [PLANS.ULTIMATE.id]: ROLE_ULTIMATE_ID,
};

module.exports = {
    PLAN_ROLE_MAP
};
